run:
  skip-files:
    - "mocks\\.go$"
  skip-dirs:
    - assets
    - build
    - test
  tests: false
  concurrency: 4
  go: '1.19'
  auto-fix: true
  autofix: true

# all available settings of specific linters
linters-settings:
  errcheck:
    check-type-assertions: true
  govet:
    check-shadowing: false
    settings:
      printf:
        funcs:
          - printf
          - debugf
          - infof
          - warnf
          - errorf
          - fatalf
          - wrapf
          - fieldalignment
  gocyclo:
    min-complexity: 25
  maligned:
    # print struct with more effective memory layout or not, false by default
    suggest-new: true
  misspell:
    locale: RU
  unparam:
    check-exported:
  wsl:
    allow-assign-and-anything: true
  gofumpt:
    lang-version: "1.19"
    auto-fix: true
    extra-rules: false
  whitespace:
    multi-if: true


linters:
  disable-all: true
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - goimports
    - revive
    - gosec
    - gofmt
    - unconvert
    - goconst
    - misspell
    - unparam
    - prealloc
    - exportloopref
    - gochecknoinits
    - gocritic
    - dupl
    - errname
    - gocyclo
    - typecheck
    - ineffassign
    - godot
    - whitespace
  #    - gofumpt
  #    - nlreturn
  #    - wsl
  fast: false

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec
        - scopelint

  max-per-linter: 0
  max-same-issues: 0
  new: false
