// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: petstore.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	github_com_mwitkow_go_proto_validators "github.com/mwitkow/go-proto-validators"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	_ "google.golang.org/protobuf/types/descriptorpb"
	_ "google.golang.org/protobuf/types/known/emptypb"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

func (this *ApiResponse) Validate() error {
	return nil
}
func (this *Category) Validate() error {
	return nil
}
func (this *Pet) Validate() error {
	if this.Category != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.Category); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("Category", err)
		}
	}
	for _, item := range this.Tags {
		if item != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(item); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("Tags", err)
			}
		}
	}
	return nil
}
func (this *Tag) Validate() error {
	return nil
}
func (this *Order) Validate() error {
	return nil
}
func (this *User) Validate() error {
	return nil
}
func (this *UploadFileRequest) Validate() error {
	return nil
}
func (this *UpdatePetRequest) Validate() error {
	if this.Body != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.Body); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("Body", err)
		}
	}
	return nil
}
func (this *AddPetRequest) Validate() error {
	if this.Body != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.Body); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("Body", err)
		}
	}
	return nil
}
func (this *FindPetsByStatusRequest) Validate() error {
	return nil
}
func (this *FindPetsByTagsRequest) Validate() error {
	return nil
}
func (this *GetPetByIdRequest) Validate() error {
	return nil
}
func (this *UpdatePetWithFormRequest) Validate() error {
	return nil
}
func (this *DeletePetRequest) Validate() error {
	return nil
}
func (this *PlaceOrderRequest) Validate() error {
	if this.Body != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.Body); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("Body", err)
		}
	}
	return nil
}
func (this *GetOrderByIdRequest) Validate() error {
	return nil
}
func (this *DeleteOrderRequest) Validate() error {
	return nil
}
func (this *GetInventoryOK) Validate() error {
	// Validation of proto3 map<> fields is unsupported.
	return nil
}
func (this *CreateUsersWithArrayInputRequest) Validate() error {
	for _, item := range this.Body {
		if item != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(item); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("Body", err)
			}
		}
	}
	return nil
}
func (this *CreateUsersWithListInputRequest) Validate() error {
	for _, item := range this.Body {
		if item != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(item); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("Body", err)
			}
		}
	}
	return nil
}
func (this *GetUserByNameRequest) Validate() error {
	return nil
}
func (this *UpdateUserRequest) Validate() error {
	if this.Body != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.Body); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("Body", err)
		}
	}
	return nil
}
func (this *DeleteUserRequest) Validate() error {
	return nil
}
func (this *LoginUserRequest) Validate() error {
	return nil
}
func (this *CreateUserRequest) Validate() error {
	if this.Body != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.Body); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("Body", err)
		}
	}
	return nil
}
